### ISSUE TITLE
headers and columns incorrect order - fields shifted +1

### ISSUE THREAD

**Issue by ghost** [torshinalexey/bitwarden-to-1password-csv#1]
Hey there 
thanks for a great solution... sadly maybe 1P or BW have changed something as the website and username cols data have shifted right , CSV columns output from your tool are as follows:

website = empty
username = has website date
password = has username (password data is missing)
notes = this is correct.

Seems like a simple one to fix for someone skilled enough, changing those 3 columns -1. I was stupid and didn't check the cols and now have nearly 1000 entries all messed up... i should have checked!

thanks

**Comment by torshinalexey** [comment]
Hello!
Thank you for the issue. Indeed set of fields in Bitwarden csv file has changed, so I've changed the code accordingly.
